# Generated by Django 4.2.11 on 2024-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
