# Generated by Django 4.2.11 on 2024-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_income_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='jumlah',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
